### ISSUE TITLE
Use container digest not config_digest

### ISSUE THREAD

**Issue by ml019** [hamlet-io/executor-python#221] opened 2021-08-24 02:26 UTC
## Expected Behaviour
When displaying container image digests via `describe-engine`, the `digest` attribute should be used

## Current Behaviour
The digest value is currently being sourced from the `config_digest` attribute

## Possible Solution
Switch the source of digests. 

## Context
- Easily relate the contents of `describe-engine` to what is shown in the `hamlet-engine-base` repo
- Avoid having to go into the manifest to find a matching value to that used in the cli.

**Comment by roleyfoley** [comment] 2021-08-24 02:27
Duplicate of #220

**Closed by roleyfoley** 2021-08-24 02:27 UTC
Labels: enhancement
